  
title:          Salafiyyah
description:    "Knowledge of Shari'ah"
baseurl:        "/"
url:            "https://alsalafiyyah.github.io"

github: [metadata]
encoding: UTF-8
permalink: pretty
paginate:       20
paginate_path: "/fatwas/:num/"
markdown:       kramdown
