  
title:          Salafiyyah
name: Salafiyyah
description:    "Knowledge of Shari'ah"
baseurl:        "/new"
url:            "https://alsalafiyyah.github.io/new/"

github: [metadata]
encoding: UTF-8
permalink: pretty
paginate:       20
paginate_path: "/fatwas/:num/"
markdown:       kramdown
