  
title:          Salafiyyah
name: Salafiyyah
description:    "Knowledge of Shari'ah"
baseurl:        "/new"
url:            "https://alsalafiyyah.github.io/new/"

github: [metadata]
encoding: UTF-8
permalink: pretty
paginate: 6
paginate_path: "/fatwas/:num/"
markdown:       kramdown

tipue_search:
  include:
    pages: false
  exclude:
    files: [index.html, search.html, sitemap.xml, feed.xml, docs, BingSiteAuth.xml, Gemfile.lock, Gemfile, manifest.yml, refutal.html, wahhabi.html, muqolat]
    
collections:
  wahhabism:
    output: true
    permalink: /new/wahabiyyah/:path/
  audios:
    output: true
    active: audios
    permalink: /new/audios/:title/
